export const SPECIALITIES = [
  "Allergy and Immunology",
  "Anatomic/Clinical Pathology",
  "Anesthesiology",
  "Cardiovascular Disease",
  "Child and Adolescent Psychiatry",
  "Critical Care Medicine",
  "Dermatology",
  "Emergency Medicine",
  "Endocrinology, Diabetes and Metabolism",
  "Family Medicine/General Practice",
  "Gastroenterology",
  "General Surgery",
  "Geriatric Medicine",
  "Hematology and Oncology",
  "Infectious Disease",
  "Internal Medicine",
  "Internal Medicine/Pediatrics",
  "Interventional Cardiology",
  "Neonatal-Perinatal Medicine",
  "Nephrology",
  "Neurological Surgery",
  "Neurology",
  "Neuroradiology",
  "Obstetrics and Gynecology",
  "Ophthalmology",
  "Orthopedic Surgery",
  "Otolaryngology",
  "Pain Medicine and Pain Management",
  "Pediatric Cardiology",
  "Pediatric Hematology/Oncology",
  "Pediatrics",
  "Physical Medicine and Rehabilitation",
  "Plastic Surgery",
  "Preventive Medicine",
  "Psychiatry",
  "Pulmonary Disease",
  "Radiation Oncology",
  "Radiology and Diagnostic Radiology",
  "Rheumatology",
  "Sports Medicine (Orthopedic Surgery)",
  "Thoracic Surgery",
  "Urology",
  "Vascular and Interventional Radiology",
  "Vascular Surgery",
];

export const SPECIALITIES_DROP_DOWN_OPTIONS = [...SPECIALITIES];

// https://cyphercodes.github.io/location-picker/
